### ISSUE TITLE
Exclude default

### ISSUE THREAD

**Issue by DaleSeo** [prodigyeducation/branch-cleaner#4]
It would make more sense for Branch Cleaner to exclude protected branches like master or develop.

**Comment by DaleSeo** [comment]
This is how to fetch default branch name from the Github GraphQL API.

```gql
query {
  repository(name: "graphql-js", owner: "graphql") {
    defaultBranchRef {
        name
    }
  }
}
```

```json
{
  "data": {
    "repository": {
      "defaultBranchRef": {
        "name": "master"
      }
    }
  }
}
```

**Comment by cy** [comment]
let me try to take a stab at this!

**Comment by DaleSeo** [comment]
@cy Glad to hear that! 🤗 
I already mentioned how to get the default branch of a repo above and for protected branches, you can use the following GraphQL query.
https://developer.github.com/v4/object/branchprotectionrule/

When you google GraphQL API, you will find more resources based on the Github API v3 than the Github API v4 since their GraphQL API is still quite new just like GraphQL itself. When I realized that Github also supports GraphQL API, I thought it would be great to use it for this project because we might learn more about GraphQL watching how other bigger companies make use of it.

Being said that, if you feel too painful to use the Github API v4, feel free to let me know!
